import {AiFillStar} from "react-icons/ai";

const data = [
{
img: "/Assets/s1.jpg",
title: "Nike Air Monarch",
star: <AiFillStar className="rating-star" />,
reviews: "(123 reviews)",
prevPrice: "$100.00",
newPrice: "80",
company: "Nike",
color: "white",
category: "sneakers",
},
{
    img: "Assets/s2.jpg",
    title: "Adidas",
    star: <AiFillStar className="rating-star" />,
    reviews: "(153 reviews)",
    prevPrice: "$40.00",
    newPrice: "30",
    company: "Adidas",
    color: "maroon",
    category: "sneakers", 
},
{
    img: "Assets/s3.jpg",
    title: "puma",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140.00",
    newPrice: "200",
    company: "Nike",
    color: "pink",
    category: "sneakers",
    },
    {
        img: "Assets/s4.jpg",
        title: "Nike Air Monarch",
        star: <AiFillStar className="rating-star" />,
        reviews: "(233 reviews)",
        prevPrice: "$120.00",
        newPrice: "100",
        company: "Nike",
        color: "white",
        category: "sneakers", 
    },
    {
        img: "Assets/s5.jpg",
        title: "vans",
        star: <AiFillStar className="rating-star" />,
        reviews: "(333 reviews)",
        prevPrice: "$140.00",
        newPrice: "110",
        company: "Vans",
        color: "halfwhite",
        category: "sneakers",
        },
        {
            img: "Assets/s6.jpg",
            title: "puma",
            star: <AiFillStar className="rating-star" />,
            reviews: "(200 reviews)",
            prevPrice: "$40.00",
            newPrice: "30",
            company: "Puma",
            color: "yellow",
            category: "flats", 
        },
        {
            img: "Assets/s7.jpg",
            title: "Nike Air Monarch",
            star: <AiFillStar className="rating-star" />,
            reviews: "(123 reviews)",
            prevPrice: "$90.00",
            newPrice: "100",
            company: "Nike",
            color: "orange",
            category: "flats",
            },
            {
                img: "Assets/s8.jpg",
                title: "Adidas",
                star: <AiFillStar className="rating-star" />,
                reviews: "(553 reviews)",
                prevPrice: "$90.00",
                newPrice: "100",
                company: "Adidas",
                color: "blue",
                category: "flats", 
            },
            {
                img: "Assets/s9.jpg",
                title: "Nike Air Monarch",
                star: <AiFillStar className="rating-star" />,
                reviews: "(123 reviews)",
                prevPrice: "$70.00",
                newPrice: "100",
                company: "Nike",
                color: "white",
                category: "flats",
                },
                {
                    img: "Assets/s10.jpg",
                    title: "vans",
                    star: <AiFillStar className="rating-star" />,
                    reviews: "(183 reviews)",
                    prevPrice: "$110.00",
                    newPrice: "150",
                    company: "Vans",
                    color: "purple",
                    category: "sneakers", 
                },
                {
                    img: "Assets/s11.jpg",
                    title: "puma",
                    star: <AiFillStar className="rating-star" />,
                    reviews: "(193 reviews)",
                    prevPrice: "$120.00",
                    newPrice: "150",
                    company: "Puma",
                    color: "black",
                    category: "sneakers", 
                },
                {
                    img: "Assets/s12.jpg",
                    title: "Puma",
                    star: <AiFillStar className="rating-star" />,
                    reviews: "(423 reviews)",
                    prevPrice: "$60.00",
                    newPrice: "50",
                    company: "Puma",
                    color: "white",
                    category: "sneakers", 
                },
                {
                    img: "Assets/s13.jpg",
                    title: "vans",
                    star: <AiFillStar className="rating-star" />,
                    reviews: "(523 reviews)",
                    prevPrice: "$120.00",
                    newPrice: "100",
                    company: "Vans",
                    color: "black",
                    category: "flats", 
                },
                {
                    img: "Assets/s14.jpg",
                    title: "Adidas",
                    star: <AiFillStar className="rating-star" />,
                    reviews: "(163 reviews)",
                    prevPrice: "$30.00",
                    newPrice: "50",
                    company: "Adidas",
                    color: "blue",
                    category: "sneakers", 
                },
                {
                    img: "Assets/s15.jpg",
                    title: "Nike",
                    star: <AiFillStar className="rating-star" />,
                    reviews: "(533 reviews)",
                    prevPrice: "$110.00",
                    newPrice: "150",
                    company: "Nike",
                    color: "white",
                    category: "sneakers", 
                },
                {
                    img: "Assets/s16.jpg",
                    title: "Puma",
                    star: <AiFillStar className="rating-star" />,
                    reviews: "(243 reviews)",
                    prevPrice: "$120.00",
                    newPrice: "150",
                    company: "Puma",
                    color: "orange",
                    category: "heels", 
                },
                {
                    img: "Assets/s17.jpg",
                    title: "Adidas",
                    star: <AiFillStar className="rating-star" />,
                    reviews: "(293 reviews)",
                    prevPrice: "$140.00",
                    newPrice: "200",
                    company: "Adidas",
                    color: "orange",
                    category: "heels", 
                },
                {
                    img: "Assets/s18.jpg",
                    title: "vans",
                    star: <AiFillStar className="rating-star" />,
                    reviews: "(353 reviews)",
                    prevPrice: "$130.00",
                    newPrice: "100",
                    company: "Vans",
                    color: "red",
                    category: "heels", 
                },
                {
                    img: "Assets/s19.jpg",
                    title: "Nike",
                    star: <AiFillStar className="rating-star" />,
                    reviews: "(323 reviews)",
                    prevPrice: "$30.00",
                    newPrice: "50",
                    company: "Nike",
                    color: "red",
                    category: "heels", 
                },   {
                    img: "Assets/s20.jpg",
                    title: "vans",
                    star: <AiFillStar className="rating-star" />,
                    reviews: "(223 reviews)",
                    prevPrice: "$140.00",
                    newPrice: "150",
                    company: "Vans",
                    color: "red",
                    category: "heels", 
                },
                {
                    img: "Assets/s21.jpg",
                    title: "adidas",
                    star: <AiFillStar className="rating-star" />,
                    reviews: "(123 reviews)",
                    prevPrice: "$140.00",
                    newPrice: "150",
                    company: "Adidas",
                    color: "white",
                    category: "sandals", 
                },
                {
                    img: "Assets/s22.jpg",
                    title: "Nike",
                    star: <AiFillStar className="rating-star" />,
                    reviews: "(423 reviews)",
                    prevPrice: "$130.00",
                    newPrice: "150",
                    company: "Nike",
                    color: "pink",
                    category: "sandals", 
                },
                {
                    img: "Assets/s23.jpg",
                    title: "vans",
                    star: <AiFillStar className="rating-star" />,
                    reviews: "(423 reviews)",
                    prevPrice: "$120.00",
                    newPrice: "150",
                    company: "Vans",
                    color: "white",
                    category: "heels", 
                },
                {
                    img: "Assets/s31.jpg",
                    title: "adidas",
                    star: <AiFillStar className="rating-star" />,
                    reviews: "(123 reviews)",
                    prevPrice: "$140.00",
                    newPrice: "200",
                    company: "Adidas",
                    color: "purple",
                    category: "sneakers", 
                },
                {
                    img: "Assets/s25.jpg",
                    title: "puma",
                    star: <AiFillStar className="rating-star" />,
                    reviews: "(123 reviews)",
                    prevPrice: "$140.00",
                    newPrice: "200",
                    company: "Puma",
                    color: "black",
                    category: "flats", 
                },   
                {
                    img: "Assets/s26.jpg",
                    title: "vans",
                    star: <AiFillStar className="rating-star" />,
                    reviews: "(123 reviews)",
                    prevPrice: "$140.00",
                    newPrice: "200",
                    company: "Vans",
                    color: "green",
                    category: "sneakers", 
                },
                {
                    img: "Assets/s27.jpg",
                    title: "vans",
                    star: <AiFillStar className="rating-star" />,
                    reviews: "(123 reviews)",
                    prevPrice: "$140.00",
                    newPrice: "200",
                    company: "Vans",
                    color: "green",
                    category: "flats", 
                },
                {
                    img: "Assets/s28.jpg",
                    title: "Nike",
                    star: <AiFillStar className="rating-star" />,
                    reviews: "(123 reviews)",
                    prevPrice: "$150.00",
                    newPrice: "300",
                    company: "Nike",
                    color: "green",
                    category: "heels", 
                },
                {
                    img: "Assets/s29.jpg",
                    title: "vans",
                    star: <AiFillStar className="rating-star" />,
                    reviews: "(123 reviews)",
                    prevPrice: "$140.00",
                    newPrice: "200",
                    company: "Vans",
                    color: "pink",
                    category: "sneakers", 
                },
                {
                    img: "Assets/s30.jpg",
                    title: "vans",
                    star: <AiFillStar className="rating-star" />,
                    reviews: "(300 reviews)",
                    prevPrice: "$180.00",
                    newPrice: "600",
                    company: "Vans",
                    color: "black",
                    category: "sneakers", 
                },
                {
                    img: "Assets/s32.jpg",
                    title: "vans",
                    star: <AiFillStar className="rating-star" />,
                    reviews: "(293 reviews)",
                    prevPrice: "$160.00",
                    newPrice: "400",
                    company: "Vans",
                    color: "white",
                    category: "heels", 
                },
                {
                    img: "Assets/s33.jpg",
                    title: "Puma soft ",
                    star: <AiFillStar className="rating-star" />,
                    reviews: "(600 reviews)",
                    prevPrice: "$200.00",
                    newPrice: "200",
                    company: "Puma",
                    color: "white",
                    category: "flats", 
                },
                {
                    img: "Assets/s34.jpg",
                    title: "vans",
                    star: <AiFillStar className="rating-star" />,
                    reviews: "(400 reviews)",
                    prevPrice: "$190.00",
                    newPrice: "500",
                    company: "Vans",
                    color: "yellow",
                    category: "falts", 
                },
                {
                    img: "Assets/s35.jpg",
                    title: "vans",
                    star: <AiFillStar className="rating-star" />,
                    reviews: "(300 reviews)",
                    prevPrice: "$140.00",
                    newPrice: "200",
                    company: "Vans",
                    color: "purple",
                    category: "flats", 
                },
                {
                    img: "Assets/s36.jpg",
                    title: "vans",
                    star: <AiFillStar className="rating-star" />,
                    reviews: "(123 reviews)",
                    prevPrice: "$180.00",
                    newPrice: "300",
                    company: "Vans",
                    color: "black",
                    category: "flats", 
                },
                {
                    img: "Assets/s37.jpg",
                    title: "vans",
                    star: <AiFillStar className="rating-star" />,
                    reviews: "(300 reviews)",
                    prevPrice: "$190.00",
                    newPrice: "400",
                    company: "Vans",
                    color: "orange",
                    category: "flats", 
                },
                {
                    img: "Assets/s38.jpg",
                    title: "Adidas flat shoes",
                    star: <AiFillStar className="rating-star" />,
                    reviews: "(500 reviews)",
                    prevPrice: "$100",
                    newPrice: "100",
                    company: "Adidas",
                    color: "green",
                    category: "flats", 
                },

];

export default data;